export class Student {
    studentId:number;
    firstName:string;
    lastName:string;
    fatherName:string;
    motherName:string;
    maleOrFemale:string;
    email:string;
    age:number;
    //enterSSCHSCmarks:number;
    phoneNumber1:number;
    phoneNumber2:number;
    houseNo:string;
    streetName:string;
    areaName:string;
    pincode:number;
    state:string;
    nationality:string;
}
